\begin{footnotesize}
\begin{pyglist}[language=text,texcl=true,abovecaptionskip=0,style=bw]
ERROR:ROOT.TFile.TFile] file file_does_not_exist.root does not exist
Traceback (most recent call last):
  File "file_open_rootpy.py.tmp.py", line 12, in <module>
    myfile = root_open("file_does_not_exist.root")
  File "/home/endw/.local/lib/python2.7/site-packages/rootpy-dev-py2.7.egg/rootpy/io/file.py", line 224, in root_open
    root_file = ROOT.TFile.Open(filename, mode)
  File "/home/endw/.local/lib/python2.7/site-packages/rootpy-dev-py2.7.egg/rootpy/io/file.py", line 224, in root_open
    root_file = ROOT.TFile.Open(filename, mode)
  File "/home/endw/.local/lib/python2.7/site-packages/rootpy-dev-py2.7.egg/rootpy/logger/roothandler.py", line 91, in python_logging_error_handler
    raise ROOTError(level, location, msg)
rootpy.ROOTError: level=3000, loc='TFile::TFile', msg='file file_does_not_exist.root does not exist'
\end{pyglist}
\end{footnotesize}
