\begin{footnotesize}
\begin{minted}{text}
ERROR:ROOT.TFile.TFile] file file_does_not_exist.root does not exist
Traceback (most recent call last):
  File "file_open_rootpy.py.tmp", line 16, in <module>
    myfile = root_open("file_does_not_exist.root")
  File "/home/endw/.local/lib/python2.7/site-packages/rootpy/io/file.py", line 138, in root_open
    root_file = ROOT.R.TFile.Open(filename, mode)
  File "/home/endw/.local/lib/python2.7/site-packages/rootpy/io/file.py", line 138, in root_open
    root_file = ROOT.R.TFile.Open(filename, mode)
  File "/home/endw/.local/lib/python2.7/site-packages/rootpy/logger/magic.py", line 247, in intercept_next_line
    raise exception
rootpy.ROOTError: level=3000, loc='TFile::TFile', msg='file file_does_not_exist.root does not exist'
\end{minted}
\end{footnotesize}
